name: Windows-x64-Portable-Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: npm ci
        shell: pwsh

      - name: Compile
        run: npm run compile
        shell: pwsh

      - name: Build vscode
        run: npm run gulp vscode-win32-x64
        shell: pwsh

      - name: Copy output
        run: xcopy ..\vscode-win32-x64 vscode-win32-x64 /E /I /H
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VSCode-Win32-x64
          path: vscode-win32-x64/
